<a href="https://colab.research.google.com/github/JuanRebolledo69/18-03-2024/blob/master/DeepLearning_Evaluacion_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1> Evaluacion 1 Deep Learning<h1>

Integrantes: Juan Rebolledo, Jose Gonzalez y Benjamin Torres

Seccion: 002D

Docente: Felipe Ordenes

In [ ]:
import pandas as pd

df = pd.read_csv("IMDB Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
df.shape

(50000, 2)

In [ ]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [ ]:
df['sentiment'].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

Luego de Cargar el Dataset, se indica que contiene 50.000 reseñas, 25.000 Positivas y 25.000 Negativas, no hay Nulos.

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(max_features=5000)

X = vectorizer.fit_transform(df['review']).toarray()

In [ ]:
X.shape

(50000, 5000)

Usamos "CountVectorizer" para transformar las palabras a representaciones numericas y que de esa forma el modelo pueda entenderlas, limitado a una cantidad maxima de 5.000 palabras.

In [ ]:
y = df['sentiment'].map({'positive':1, 'negative':0})

In [ ]:
y.head()

0    1
1    1
2    1
3    0
4    1
Name: sentiment, dtype: int64

Ahora transformamos las reseñas a numeros para la comprension del Modelo. Las Positivas como "1" y las Negativas como "0".

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
X_train.shape

(40000, 5000)

Se dividio el Dataset en dos partes y se asigno el 80% de los datos para entrenamiento y el 20% restante para pruebas y evaluacion. De esa forma comprobamos si el Modelo realmente aprendio o solo memorizo.

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()

model.add(Dense(16, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Se contruye una red neuronal con Keras, con una arquitectura que consiste en una capa de entrada, conectada a una capa oculta de 16 neuronas con activacion ReLU, que continua a una segunda capa oculta de 8 neuronas y finalmente se utiliza la capa de salida con una neurona y Sigmoide para realizar la clasificacion binaria de Positiva o Negativo.

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │        80,016 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 80,161 (313.13 KB)

 Trainable params: 80,161 (313.13 KB)

 Non-trainable params: 0 (0.00 B)

80.161 Parametros entrenables.

<H1> Entrenamiento 1: <H1>

3 Epocas / Batch 32

In [ ]:
model.fit(X_train, y_train, epochs=3, batch_size=32)

Epoch 1/3
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.8685 - loss: 0.3243
Epoch 2/3
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.9072 - loss: 0.2313
Epoch 3/3
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.9194 - loss: 0.1978

In [ ]:
model.evaluate(X_test, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8801 - loss: 0.3000

[0.2999568581581116, 0.8801000118255615]

In [ ]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)

print(classification_report(y_test, y_pred))

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
              precision    recall  f1-score   support

           0       0.88      0.89      0.89      4970
           1       0.89      0.88      0.89      5030

    accuracy                           0.89     10000
   macro avg       0.89      0.89      0.89     10000
weighted avg       0.89      0.89      0.89     10000

Se evaluo al Modelo con el conjunto de datos apartados para Pruebas con 3 Epocas y se obtuvo una presicion (accuracy) cercana al 88% de acierto y un valor de perdida (loss) de 0.30, un valor relativamente bajo. Este resultado indica que el Modelo es capaz de clasificar correctamente la mayoria de las reseñas.

<H1> Entrenamiento 2: <H1>

5 Epocas / Batch 32

In [ ]:
model.fit(X_train, y_train, epochs=5, batch_size=32)

Epoch 1/5
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.9295 - loss: 0.1696
Epoch 2/5
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.9442 - loss: 0.1368
Epoch 3/5
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.9588 - loss: 0.1055
Epoch 4/5
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.9706 - loss: 0.0774
Epoch 5/5
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.9807 - loss: 0.0559

In [ ]:
model.evaluate(X_test, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8720 - loss: 0.5832

[0.5831872820854187, 0.871999979019165]

In [ ]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)

print(classification_report(y_test, y_pred))

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
              precision    recall  f1-score   support

           0       0.87      0.87      0.87      4970
           1       0.87      0.88      0.87      5030

    accuracy                           0.87     10000
   macro avg       0.87      0.87      0.87     10000
weighted avg       0.87      0.87      0.87     10000

Luego de entrenar por segunda vez el modelo, esta vez con 5 Epocas, la presicion bajo a 87% y el valor de perdida (loss) subio a 0.53.

<H1> Entrenamiento 3: <H1>

3 Epocas / Batch 64

In [ ]:
model.fit(X_train, y_train, epochs=3, batch_size=64)

Epoch 1/3
625/625 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.9920 - loss: 0.0280
Epoch 2/3
625/625 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9972 - loss: 0.0153
Epoch 3/3
625/625 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.9986 - loss: 0.0095

In [ ]:
model.evaluate(X_test, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8699 - loss: 0.8737

[0.8737049698829651, 0.8698999881744385]

In [ ]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)

print(classification_report(y_test, y_pred))

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
              precision    recall  f1-score   support

           0       0.86      0.88      0.87      4970
           1       0.88      0.86      0.87      5030

    accuracy                           0.87     10000
   macro avg       0.87      0.87      0.87     10000
weighted avg       0.87      0.87      0.87     10000

Esta vez, nuevamente entrenamos al Modelo con 3 Epocas, pero cambiamos el tamaño del Batch a 64, dando como resultado una precision del 87% y un valor de perdida (loss) de 0.80.

<h1> Comparacion de los 3 Entrenamientos <h1>

Luego de Entrenar al Modelo tres veces variando la cantidad de Epocas y el tamaño del Batch, podemos ver que la version con 3 Epocas y Batch de 32 dio un mejor resultado con un 88% de presicion y un valor de perdida de 0.30, mientras que al entrenarlo con mas Epocas y mas tamaño de Batch, su presicion dsiminuyo y su valor de perdida (loss) aumento.

Esto sugiere que entrenar al modelo mas tiempo, no necesariamente mejora su rendimiento.

<H1> Conclusion <H1>

En este trabajo, se desarrollo una red neuronal para clasificar reseñas de peliculas.

Se realizo preprocesamiento del texto con vectorizacion para interpretarlo de forma numerica para la comprension del Modelo.

Se entreno al modelo y se evaluo en 3 situaciones distintas, variando la cantidad de Epocas y el tamaño del Batch.

Los resultados mostraron que una configuracion simple de parametros, fue la que dio un mejor resultado (3 Epocas y Batch Size 64).

Esto demuestra que aumentar la complejidad del entrenamiento no siempre mejora los resultados, siendo fundamental encontrar un equilibrio adecuado en los parametros del modelo.